### ISSUE TITLE
 No rule to make target 'install'

### ISSUE THREAD

**Issue by grandrea** [rjdkmr/gmx_hole#2]
Hello,
I am trying to compile gmx_hole. After executing the cmake step in the build directory, I get:

-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libgromacs'
--   Found libgromacs, version 2018.3
-- Found fftw library:/path_to/gromacs-2018.3/build/src/contrib/fftw/fftwBuild-prefix/lib/libfftw3f.a
-- Found z library: /usr/lib/x86_64-linux-gnu/libz.so
-- Found GROMACS: /usr/local/gromacs/lib/libgromacs.so  
-- Found Gromacs include directory: /usr/local/gromacs/include
-- Configuring done
-- Generating done
-- Build files have been written to: /path_to/gmx_hole/build

however, when I type make and then make install within the build directory , I get:

make: *** No rule to make target 'install'.  Stop.

Thank you

**Comment by rjdkmr** [comment]
Hi,

I have not checked installation for GROMACS 2018.3 version. What was the error when make command was issued?

**Comment by grandrea** [comment]
Thanks for the quick reply!
The make command did not give any error, but also no output whatsoever

**Comment by rjdkmr** [comment]
Sorry for the late reply.

I have updated the package for GROMACS-2018 version. Now it should works.

Thanks.
